from detectron2.config import CfgNode as CN

def add_default_config(cfg):
    _C = cfg
    _C.INPUT.FORMAT = "RGB"
    _C.INPUT.MIN_SIZE_TRAIN = 513
    _C.INPUT.MAX_SIZE_TRAIN = 513
    _C.INPUT.MIN_SIZE_TEST = 513
    _C.INPUT.MAX_SIZE_TEST = 513
    _C.INPUT.NUM_CLASSES = 80
    _C.INPUT.MASK_ON = True
    _C.INPUT.NUM_CANDIDATE = 128
    
    #STEM
    _C.MODEL.STEM_BLOCK = CN()
    _C.MODEL.STEM_BLOCK.IN_CHANNELS  = 3
    _C.MODEL.STEM_BLOCK.OUT_CHANNELS = 64

    #MSA
    _C.MODEL.MSA_BLOCK = CN()
    _C.MODEL.MSA_BLOCK.IN_CHANNELS  = 64
    _C.MODEL.MSA_BLOCK.OUT_CHANNELS = 64
    _C.MODEL.MSA_BLOCK.WS_RATIO     = 0.1

    #BACKBONE
    _C.MODEL.PELEENET = CN()
    _C.MODEL.PELEENET.IN_CHANNELS = 64
    _C.MODEL.PELEENET.GROWTH_RATE = 32
    _C.MODEL.PELEENET.BLOCK_CONFIG = [3,4,8,6]
    _C.MODEL.PELEENET.BOTTLENECK_WIDTH = [1,2,4,4]
    _C.MODEL.PELEENET.DROPOUT_RATE = 0.05
    _C.MODEL.PELEENET.PREDICT_LAYER  = [2,4,8,11]

    #HEAD
    _C.MODEL.HEAD = CN()
    _C.MODEL.HEAD.IN_CHANNELS = 64
    _C.MODEL.HEAD.BIAS_VALUES = -2.19

    #CENTER NOTATION
    _C.MODEL.CENTER_NOTATION = CN()
    _C.MODEL.CENTER_NOTATION.DOWN_SCALE = 4
    _C.MODEL.CENTER_NOTATION.OUT_CHANNELS = (129,129)
    _C.MODEL.CENTER_NOTATION.TENSOR_DIM = 129
    _C.MODEL.CENTER_NOTATION.MIN_OVERLAP = 0.7

    #LOSSES
    _C.MODEL.LOSSES = CN()
    _C.MODEL.LOSSES.CLASS_WEIGHT = 1
    _C.MODEL.LOSSES.WH_WEIGHT = 0.5
    _C.MODEL.LOSSES.XY_WEIGHT = 1
    
    #Default Dataset config
    _C.DATASETS = CN()
    _C.DATASETS.NAME  = "coco"
    _C.DATASETS.TRAIN = ("coco_2017_train",)
    _C.DATASETS.TEST  = ("coco_2017_val",)
    _C.DATASETS.CROP_ENABLE = True   
    _C.DATASETS.CROP_TYPE = "absolute"
    _C.DATASETS.CROP_SIZE = (513,513)

    #Default SOLVER Config
    _C.SOLVER = CN()
    _C.SOLVER.IMS_PER_BATCH = 16
    _C.SOLVER.OPTIMIZER = "SGD"
    _C.SOLVER.MOMENTUM = 0.9
    _C.SOLVER.LR_SCHEDULER_NAME = "WarmupMultiStepLR"
    _C.SOLVER.WARMUP_METHOD = "linear"
    _C.SOLVER.GAMMA= 0.1
    _C.SOLVER.CHECKPOINT_PERIOD= 5000
    _C.SOLVER.BASE_LR = 0.0001
    _C.SOLVER.BACKBONE_MULTIPLIER = 0.01
    _C.SOLVER.STEPS = (369600,)
    _C.SOLVER.MAX_ITER = 554400
    _C.SOLVER.WARMUP_FACTOR = 0.1
    _C.SOLVER.WARMUP_ITERS  = 10
    _C.SOLVER.WEIGHT_DECAY = 0.0001
    _C.SOLVER.CLIP_GRADIENTS = CN()
    _C.SOLVER.CLIP_GRADIENTS.ENABLED = False
    _C.SOLVER.CLIP_GRADIENTS.CLIP_TYPE= "full_mode"
    _C.SOLVER.CLIP_GRADIENTS.CLIP_VALUE= 0.01
    _C.SOLVER.CLIP_GRADIENTS.NORM_TYPE= 2.0
    _C.SOLVER.REFERENCE_WORLD_SIZE = 0
